site_name: Hesiod Documentation

theme:
  name: material
  favicon: images/favicon.ico
  palette:
    - scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  features:
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - search.suggest
    - content.code.copy
    - toc.follow

plugins:
  - search
  - literate-nav:
      nav_file: SUMMARY.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

exclude_docs: |
  *.in.md

nav:
  - 'Start Here':
    - 'index.md'
  - 'Core Concepts':
    - 'core_concepts/index.md'
    - 'core_concepts/heightmaps.md'
    - 'core_concepts/masks-selectors.md'
    - 'core_concepts/broadcast-receive.md'
  - 'User Manual':
    - 'user_manual/index.md'
    - 'user_manual/node_settings/node_settings_management.md'
    - 'user_manual/bake_and_export/bake_and_export.md'
    - 'user_manual/coordinate_system/index.md'
    - 'user_manual/patch-of-graphs.md'
    - 'Using Physics-Based Procedures':
      - 'user_manual/using_physics_based_procedures/index.md'
      - 'Hydrology':
        - 'user_manual/using_physics_based_procedures/hydrology/index.md'
        - 'user_manual/using_physics_based_procedures/hydrology/flooding/index.md'
  - 'Node Reference': 'node_reference/'
  - 'FAQ':
    - 'faq/index.md'
