site_name: Hesiod Documentation

theme:
  name: material
  favicon: images/favicon.ico
  palette:
    - scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  features:
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - search.suggest
    - content.code.copy
    - toc.follow

plugins:
  - search
  - literate-nav:
      nav_file: SUMMARY.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

exclude_docs: |
  *.in.md

nav:
  - 'Start Here':
    - 'index.md'
  - 'Node Reference': 'node_reference/'
