/* Copyright (c) 2023 Otto Link. Distributed under the terms of the GNU General
 * Public License. The full license is in the file LICENSE, distributed with
 * this software. */
#include "hesiod/gui/widgets/graph_config_widgets/bake_config_dialog.hpp"
#include "hesiod/app/hesiod_application.hpp"
#include "hesiod/gui/widgets/gui_utils.hpp"

namespace hesiod
{

BakeConfigDialog::BakeConfigDialog(int               max_size,
                                   const BakeConfig &initial_value,
                                   QWidget          *parent)
    : QDialog(parent)
{
  this->setWindowTitle("Bake and export settings");
  this->setModal(true);

  this->resolution_combo = new QComboBox(this);
  this->slider = new QSlider(Qt::Horizontal, this);
  this->slider_nvariants = new QSpinBox(this);
  this->checkbox_force_distributed = new QCheckBox("Force distributed computation", this);
  this->checkbox_force_auto_export = new QCheckBox("Force auto export for export nodes",
                                                   this);
  this->checkbox_rename_export_files = new QCheckBox("Add prefix export filenames", this);
  this->checkbox_force_maximum_fbm_octaves = new QCheckBox(
      "Force maximum number of octaves for Fbm nodes",
      this);

  this->buttons = new QDialogButtonBox(QDialogButtonBox::Ok | QDialogButtonBox::Cancel,
                                       this);

  // Fill power-of-two options up to max_size
  for (int size = 2; size <= max_size; size *= 2)
  {
    this->resolution_combo->addItem(QString("%1").arg(size), size);
  }
  this->resolution_combo->setCurrentIndex(
      this->resolution_combo->findData(initial_value.resolution));

  // Setup slider + spinbox
  this->slider->setRange(0, 50);
  this->slider_nvariants->setRange(0, 50);
  this->slider_nvariants->setValue(initial_value.nvariants);
  this->slider->setValue(initial_value.nvariants);

  QObject::connect(this->slider,
                   &QSlider::valueChanged,
                   this->slider_nvariants,
                   &QSpinBox::setValue);
  QObject::connect(this->slider_nvariants,
                   QOverload<int>::of(&QSpinBox::valueChanged),
                   this->slider,
                   &QSlider::setValue);

  // Checkbox default state (input parameter)
  this->checkbox_force_distributed->setChecked(initial_value.force_distributed);
  this->checkbox_force_auto_export->setChecked(initial_value.force_auto_export);
  this->checkbox_rename_export_files->setChecked(initial_value.rename_export_files);
  this->checkbox_force_maximum_fbm_octaves->setChecked(
      initial_value.force_maximum_fbm_octaves);

  // Large graphs & memory optimization group
  auto *group_memory = new QGroupBox("Large Graphs and Memory Optimization", this);
  auto *group_layout = new QVBoxLayout(group_memory);

  this->checkbox_min_memory = new QCheckBox("Low memory mode", this);
  this->checkbox_min_memory->setChecked(initial_value.min_memory);
  group_layout->addWidget(this->checkbox_min_memory);

  auto *tile_layout = new QHBoxLayout;
  tile_layout->addWidget(new QLabel("Max tile shape:", this));
  this->combo_max_tile_resolution = new QComboBox(this);
  for (int size = 128; size <= max_size; size *= 2)
  {
    this->combo_max_tile_resolution->addItem(QString("%1").arg(size), size);
  }
  int tile_idx = this->combo_max_tile_resolution->findData(
      initial_value.max_tile_resolution);
  if (tile_idx != -1)
    this->combo_max_tile_resolution->setCurrentIndex(tile_idx);
  else
    this->combo_max_tile_resolution->setCurrentIndex(
        this->combo_max_tile_resolution->findData(32768));

  tile_layout->addWidget(this->combo_max_tile_resolution);
  group_layout->addLayout(tile_layout);

  std::string note_style = std::format(
      "color: {};",
      HSD_CTX.app_settings.colors.text_secondary.name().toStdString());

  QLabel *label_memory_note = new QLabel(
      "Reduces RAM usage by streaming tiles to disk and evaluating sequentially. "
      "Recommended for very large graphs, but baking will be slower.",
      this);
  label_memory_note->setStyleSheet(note_style.c_str());
  label_memory_note->setWordWrap(true);
  resize_font(label_memory_note, -1);
  group_layout->addWidget(label_memory_note);

  // Layout
  auto *form_layout = new QFormLayout;
  form_layout->addRow("Resolution (x):", this->resolution_combo);

  auto *slider_layout = new QHBoxLayout;
  slider_layout->addWidget(this->slider);
  slider_layout->addWidget(this->slider_nvariants);
  form_layout->addRow("Additional variants:", slider_layout);

  QLabel *label_variants_note = new QLabel(
      "Additional variants of the initial setup are generated by randomizing seed "
      "values, keeping the same procedural algorithm while producing variations.",
      this);
  label_variants_note->setStyleSheet(note_style.c_str());
  label_variants_note->setWordWrap(true);
  resize_font(label_variants_note, -1);
  form_layout->addRow(label_variants_note);

  auto *main_layout = new QVBoxLayout;
  main_layout->addLayout(form_layout);
  main_layout->addWidget(this->checkbox_force_distributed);
  main_layout->addWidget(this->checkbox_force_auto_export);
  main_layout->addWidget(this->checkbox_rename_export_files);
  main_layout->addWidget(this->checkbox_force_maximum_fbm_octaves);
  main_layout->addWidget(group_memory);
  main_layout->addWidget(this->buttons);
  this->setLayout(main_layout);

  QObject::connect(this->buttons, &QDialogButtonBox::accepted, this, &QDialog::accept);
  QObject::connect(this->buttons, &QDialogButtonBox::rejected, this, &QDialog::reject);
}

BakeConfig BakeConfigDialog::get_bake_settings() const
{
  BakeConfig config;
  config.resolution = this->resolution_combo->currentData().toInt();
  config.nvariants = this->slider_nvariants->value();
  config.force_distributed = this->checkbox_force_distributed->isChecked();
  config.force_auto_export = this->checkbox_force_auto_export->isChecked();
  config.rename_export_files = this->checkbox_rename_export_files->isChecked();
  config.force_maximum_fbm_octaves = this->checkbox_force_maximum_fbm_octaves
                                         ->isChecked();
  config.min_memory = this->checkbox_min_memory->isChecked();
  config.max_tile_resolution = this->combo_max_tile_resolution->currentData().toInt();
  return config;
}

} // namespace hesiod
